name: CMake_windows_MSVC

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Create Build Environment
      run: cmake -E make_directory "${{github.workspace}}\build"
      
    - name: Get number of CPU cores
      uses: SimenB/github-actions-cpu-cores@v1
      id: cpu-cores
      
    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: msys2 {0}
      working-directory: ${{github.workspace}}\build
      run: cmake $GITHUB_WORKSPACE -G "Visual Studio 17 2022" -D CMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      shell: msys2 {0}
      working-directory: ${{github.workspace}}\build
      run: cmake --build . -j ${{steps.cpu-cores.outputs.count}} --config $BUILD_TYPE

    - name: Test
      shell: msys2 {0}
      working-directory: ${{github.workspace}}\build
      run: ctest -C $BUILD_TYPE --verbose
